language: python

# sudo false implies containerized builds
sudo: false

python:
  - 3.5
  - 3.6

# command to install dependencies
install:
  - pip install -r requirements.txt

script:
  - python bop/test_bop.py
